import Document, {
  DocumentContext,
  Head,
  Html,
  Main,
  NextScript,
} from "next/document";
import { ServerStyleSheet } from "styled-components";

class _Document extends Document {
  static async getInitialProps(ctx: DocumentContext) {
    return await Document.getInitialProps(ctx);
  }
  render() {
    return (
      <Html lang="en-Us">
        <Head>
          <link rel="shortcut icon" href="/static/images/favicon.ico" />
          <link
            href="https://fonts.googleapis.com/css2?family=Montserrat:wght@400;500;600;700&display=swap"
            rel="stylesheet"
          />
          <meta name="description" content="Generated by Next JS" />
        </Head>
        <body className="body-document">
          <Main />
          <NextScript />
        </body>
      </Html>
    );
  }
}

export default _Document;
